<footer id="dol-footer" class="group">

  	<div id="dol-footer-inner" class="container_16 ">
  				
		<div class="grid_3">
			<h4>About Us</h4>
				<ul >
					<li><a href="/about/">Overview</a></li>
					<li><a href="/about/history.shtm">Our History</a></li>
					<li><a href="/about/services.shtm">Our Services</a></li>
				</ul>	

            <h4>Divisions</h4>
			<ul >
				<li><a href="/dews-index.shtm">Employment &amp; <br/>Workforce Solutions</a></li>
				<li><a href="/equal-opportunity/index.shtm">Equal Opportunity</a></li>
				<li><a href="/immigrants">Immigrant Policies &amp; Affairs</a></li>
				<li><a href="/stats/index.shtm">Research &amp; Statistics</a></li>
				<li><a href="/legal/">Legal</a></li>
				<li><a href="/information-technology/index.shtm">Planning &amp; Technology</a></li>
				<li><a href="/ui/ui_index.shtm">Unemployment Insurance</a></li>
				<li><a href="/workerprotection/wp_index.shtm">Worker Protection</a></li>
			</ul> 
		</div>
  				
 				
  				
        <div class="grid_3" >

		<h4>Boards</h4>
			<ul >
				<li><a href="/erb/index.shtm">Employment Relations Board</a></li>
				<li><a href="/hab/index.htm">Hazard Abatement Board</a></li>
				<li><a href="/iba/index.asp">Industrial Board of Appeals</a></li>
				<li><a href="/workforcenypartners/lwia.shtm">Local Workforce <br />Investment Boards</a></li>
				<li><a href="/workforce/swib/SWIBAbout.shtm">State Workforce <br />Investment Board</a></li>
				<li><a href="/ui-appeal/">Unemployment Insurance <br/>Appeal Board</a></li>
			</ul>
        </div> 

		<div class="grid_3" style="">
			<h4>Newsroom</h4>
			<ul >
				<li><a href="/pressreleases/pressreleases.shtm">Press Releases &amp; Public Notices</a></li>
				<li><a href="/agencyinfo/publicmeeting.shtm">Public Meetings</a></li>
				<li><a href="/workforcenypartners/warn/warnportal.shtm">WARN Notices</a></li>
			</ul>

			<h4>Initiatives</h4>
			<ul >
				<li><a href="/apprenticeship/appindex.shtm">Apprenticeship</a></li>
				<li><a href="http://careerzone.ny.gov">CareerZone</a></li>
				<li><a href="http://www.greencareersny.com">Green Jobs</a></li>
				<li><a href="http://jobzone.ny.gov">JobZone</a></li>
				<li><a href="http://nyworks.ny.gov/">Regional Economic Development Councils</a></li>
				<li><a href="http://ridesafeny.com">Ride Safe NY</a></li>
				<li><a href="/ui/employerinfo/shared-work-program.shtm">Shared Work</a></li>
				<li><a href="/youth">Youth Portal</a></li>
			</ul> 
		</div>        
		
		<div id="footer-contact" class="grid_4 prefix_1 ">
			<div id="contact-border"></div>			
			<h4>Contact Us</h4>

			<h5>Unemployment Insurance (UI)</h5>
				<p class="list-header"><a href="/ui/claimantinfo/ContactInfo.shtm">Individual UI Claim Assistance</a></p>
				<ul>
					<li>(888) 209-8124</li>
					<li>(877) 358-5306 (Outside NYS)</li>
				</ul>
				<p><a href="/ui/claimantinfo/ContactInfo.shtm">Other UI Contact Information</a></p>

			<h5>NY.GOV ID Assistance</h5>						
				<ul>
					<li>(800) 833-3000</li>
				</ul>
			<h5>General Inquiries<span class="ux-header-subtitle">Unrelated to Individual UI claim assistance</span></h5>				
				<ul>
					<li>(518) 457-9000</li>
					<li>(888) 4-NYSDOL (888-469-7365)</li>
					<li>(800) 662-1220 (TTY/TTD) </li>
					<li>
						<a class="button_mini email" href="/secure/contact">E-mail</a>
					</li>
				</ul>

			<address>
				NYS Department of Labor<br/>
				Building 12<br/>
				W.A. Harriman Campus<br/>
				Albany, NY 12240
			</address>
		</div>    	
		<div id="footer-quick-nav" class="grid_2">

								
			<a class="button flag" style="width: 85px; margin-left: -10px;" href="/agencyinfo/report-fraud.shtm">Report Fraud</a>

			<div id="footer-policies" >

				<ul>
						<li><a href="https://www.labor.ny.gov/secure/foilrequest.shtm">FOIL Request</a></li>
						<li><a href="/agencyinfo/accessibility.shtm">Accessibility Policy</a></li>
						<li><a href="/privacy.shtm">Privacy Policy</a></li>
						<li><a href="/utilities/document-readers.shtm">Get Adobe Reader</a></li>
				</ul>

			</div> 
 
			<div id="stay-connected">
				<ul> 
					<li><a href="http://www.facebook.com/nyslabor" id="facebook" target="_blank" class="ux-no-link-icon">Facebook</a></li>
					<li><a href="http://www.youtube.com/user/NYSLabor" id="youtube" target="_blank" class="ux-no-link-icon">YouTube</a></li>
					<li><a href="http://twitter.com/nyslabor" id="twitter" target="_blank" class="ux-no-link-icon">Twitter</a></li>
					<li><a href="http://www.flickr.com/photos/nyslabor/" id="flickr" target="_blank" class="ux-no-link-icon">Flickr</a></li>
				</ul>
			</div>
		</div>
		<p id="dol-footer-equal" class="align-right margin-top grid_16">The New York State Department of Labor is an Equal Opportunity Employer/Program. Auxiliary aids and services are available upon request to individuals with disabilities.</p>
	</div>  <!-- end foot-inner -->
  				
  	
  				




</footer> <!-- end #footer -->
