
			
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Job Seekers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Job Seekers</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/findajob/jobfairrecruitmentsindex.shtm">Career Fairs and Recruitments</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/CareerServicesIndex.shtm">Find a Job</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/osview.asp">New York State Career Centers</a>
											</li>
											<li>
												<strong >Apprenticeship</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/registration.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/occupations.shtm">Active Trades</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/pressreleases/apprenticeshiparchive.shtm">Current Recruitments</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Career Development</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/planningyourcareerindex.shtm">Overview</a>
											</li>
											<li>
												<a href="http://careerzone.ny.gov/">CareerZone</a>
											</li>
											<li>
												<a href="http://jobzone.ny.gov/">JobZone</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lstrain.shtm">Occupational Licenses and Certifications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/findajob/res_fun.shtm">Resumes</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/training.shtm">Training</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Youth</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/youth">Information Portal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor Law</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/secure/child_index.shtm">Child Performer</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/wphmpg.shtm">Working Papers</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Labor Statistics</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lscesmaj.shtm">Current Employment Statistics</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/demand.asp">Growing Occupations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Jobs Press Release</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Unemployment</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Online Services</strong>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Check Payment History</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Claim Weekly Benefits</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">File a Claim</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Print 1099</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Register for Direct Deposit</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Links</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/UIBenefitsCalculator.shtm">Benefits Calculator</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/ExtendedBenefits.shtm">Extended Benefits</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/unemploymentassistance.shtm">Unemployment Assistance</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Documents</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/Claimant%20Handbook%20-%20Languages.shtm">Claimant Handbook</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/claimant-forms-and-publications.shtm">Forms and Publications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/faq.shtm">Frequently Asked Questions</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Wages/Breaks</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/meals.shtm">Breaks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wage</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm#4">Overtime</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Wage Rates</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Public Work</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Equal Opportunity</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/how-to-file-a-discrimination-claim.shtm">File a Discrimination Complaint</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong>Work For Success</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/work-for-success/">Work For Success Program Overview</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Veterans</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/vets/vetintropage.shtm">Veterans' Services</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Immigrants</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Division of Immigrant Policies and Affairs</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Legal Updates</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
	