<nav class="container_16 ux-content" id="app-nav">
	<ul>
		<li>
			<a href="http://labor.ny.gov">Home</a>
		</li>
		<li>
			<a href="http://labor.ny.gov/main/individuals.asp">Individuals</a>
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Job Seekers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Job Seekers</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/findajob/jobfairrecruitmentsindex.shtm">Career Fairs and Recruitments</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/CareerServicesIndex.shtm">Find a Job</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/osview.asp">New York State Career Centers</a>
											</li>
											<li>
												<strong >Apprenticeship</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/registration.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/occupations.shtm">Active Trades</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/pressreleases/apprenticeshiparchive.shtm">Current Recruitments</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Career Development</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/planningyourcareerindex.shtm">Overview</a>
											</li>
											<li>
												<a href="http://careerzone.ny.gov/">CareerZone</a>
											</li>
											<li>
												<a href="http://jobzone.ny.gov/">JobZone</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lstrain.shtm">Occupational Licenses and Certifications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/findajob/res_fun.shtm">Resumes</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/planyourcareer/training.shtm">Training</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Youth</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/youth">Information Portal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor Law</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/secure/child_index.shtm">Child Performer</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/wphmpg.shtm">Working Papers</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Labor Statistics</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lscesmaj.shtm">Current Employment Statistics</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/demand.asp">Growing Occupations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Jobs Press Release</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Unemployment</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Online Services</strong>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Check Payment History</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Claim Weekly Benefits</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">File a Claim</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Print 1099</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/Individual/">Register for Direct Deposit</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Links</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/UIBenefitsCalculator.shtm">Benefits Calculator</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/ExtendedBenefits.shtm">Extended Benefits</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/unemploymentassistance.shtm">Unemployment Assistance</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Important Documents</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/claimantinfo/Claimant%20Handbook%20-%20Languages.shtm">Claimant Handbook</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/claimant-forms-and-publications.shtm">Forms and Publications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/faq.shtm">Frequently Asked Questions</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workers</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Wages/Breaks</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/meals.shtm">Breaks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wage</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm#4">Overtime</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Wage Rates</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Public Work</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Equal Opportunity</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/how-to-file-a-discrimination-claim.shtm">File a Discrimination Complaint</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong>Work For Success</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/work-for-success/">Work For Success Program Overview</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Veterans</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/vets/vetintropage.shtm">Veterans' Services</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Immigrants</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Division of Immigrant Policies and Affairs</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Legal Updates</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		</li>
		<li>
			<a href="http://labor.ny.gov">Businesses</a>
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Unemployment Insurance</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employer.shtm">Employer Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">Unemployment Insurance Online Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/registering-for-unemployment-insurance.shtm">Registering</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/interest-assessment-surcharge.shtm">Interest Assessment Surcharge</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/quarterly-reporting.shtm">Quarterly Reporting</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/tax-rate-information.shtm">Tax Rate Information</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/employer-forms-publications.shtm">Forms and Publications</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/shared-work-program.shtm">The Shared Work Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Recruitment Services</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Recruitment Services</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/lookforworkers/lookingforworkersIndex.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/job-fairs.shtm">Career Fairs and Recruitments</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/perm.shtm">Place a Job Order</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Manage Your Workforce</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/servicesindex.shtm">Consultation Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/agriculture-labor-program/services-for-agriculture-employers.shtm">Services for Agricultural Employers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/funding.shtm">Funding Opportunities</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/ETPL/">Eligible Training Providers</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Hiring Incentives</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/services/fbp.shtm">Federal Bonding Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/ojt.shtm">On-the-Job Training</a>
											</li>
											<li>
												<a href="http://www.labor.ny.gov/careerservices/work-for-success/">Work For Success Program</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/edsu/edsu%20wotc.shtm">Work Opportunity Tax Credit</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Apprenticeship</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/appsponsor.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/sponsor/index.asp">Active Sponsors List</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/atc.shtm">Apprenticeship and Training Council</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/activesponsorlist.shtm#dereg">Deregistered/Closed Programs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/general/lawsandregs.shtm">Laws and Regulations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/pending-approval.shtm">Programs Pending Approval</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Labor Statistics</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lseeo.shtm">Affirmative Action Data</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Occupational Wages</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Labor Law</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/adjudication-decisions.shtm">Adjudication Decisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minors.shtm">Child Labor</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/foilrequest.shtm">FOIL Requests</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal Frequently Asked Questions</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/counsel-opinion-letters.shtm">Legal Opinions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWGeneralProvisions.shtm">Public Work - General Provisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notices</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Worker Protection</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Labor Standards</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/labor_standards.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/garment.asp">Apparel Industry</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/farm_labor.shtm">Farm Labor</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Immigrants and Non-English Speakers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/wpcpu.shtm">Licenses, Permits, Certifications</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/posters.shtm">Required Posters</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Safety & Health</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_INDEX.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_BOARDS.shtm">Boards and Councils</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_CODE_RULES.shtm">Codes and Regulations</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_PROGRAMS.shtm">Special Programs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/workplaceviolence.shtm ">Workplace Violence Prevention</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Wages/Breaks</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/employer/meals.shtm">Breaks</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm">Minimum Wage</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm#4">Overtime</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/lswage2.asp">Wage Rates</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Public Work</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWDebarmentInformation.shtm">Debarred List</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Online Services</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="https://wps.labor.state.ny.us/WPS_Curam/en/WPEmployer_ExternalhomePage.do">Asbestos Notifications</a>
											</li>
											<li>
												<a href="https://applications.labor.ny.gov/eRegWeb/">Register for Unemployment Insurance (NYS-100)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">Unemployment Insurance Online Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/Authentication/index.shtm">File a Quarterly Report (NYS-45)</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Immigrants</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Division of Immigrant Policies and Affairs</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		</li>
		<li>
			<a href="http://labor.ny.gov">Government & Research</a>
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">Labor Statistics</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Labor Statistics Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/green/index.shtm">Green Jobs Survey</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/prlaus.shtm">Monthly Press Release - Local Area Unemployment Rates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Press Release - Statewide Jobs Data</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workforce Investment Act</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/lwia.shtm">Local Workforce Investment Boards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforce/swib/SWIBAbout.shtm">State Workforce Investment Board</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Legal</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/adjudication-decisions.shtm">Adjudication Decisions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/counsel-opinion-letters.shtm">Counsel Letters</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Frequently Asked Questions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/legal-updates.shtm">Legal Updates</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Public Work</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWContents.shtm">Overview</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChanges.do?method=showIt">Article 8 - Construction</a>
											</li>
											<li>
												<a href="http://wpp.labor.state.ny.us/wpp/publicViewPWChangesArt9.do?method=showIt">Article 9 - Building Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PWDebarmentInformation.shtm">Debarred List</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		</li>
		<li>
			<a href="http://labor.ny.gov">Other Information</a>
			<div class="sub-nav outer-sub-nav">
				<nav class="container_16 ux-content">
					<ul>
						<li>
							<a href="#">About Us</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >About Labor</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/index.shtm">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/history.shtm">Our History</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/about/services.shtm">Our Services</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Contact Us</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/contact">Overview</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/how-to-file-a-discrimination-claim.shtm">File Discrimination Complaint</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/secure/foilrequest.shtm">FOIL Request</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/agencyinfo/report-fraud.shtm">Report Fraud</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/warn/warnportal.shtm">WARN Notice</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Divisions</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<strong >Divisions</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/dews-index.shtm">Employment & Workforce Solutions</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/equal-opportunity/index.shtm">Equal Opportunity</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/immigrants/index.shtm">Immigrant Policies & Affairs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/index.shtm">Legal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/information-technology/index.shtm">Planning & Technology</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/index.shtm">Research & Statistics</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/unemploymentassistance.shtm">Unemployment Insurance</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/wp_index.shtm">Worker Protection</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Department FAQs</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/laborstandards/faq.shtm">Wages & Hours</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/publicwork/PW_faq1.shtm">Prevailing Wage/Public Work</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/faq.shtm">Safety and Health</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/faq.shtm">Unemployment (Claimants)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/frequently-requested-information.shtm">Unemployment (Employers)</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<strong >Newsroom</strong>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/prlaus.shtm">Monthly Press Release - Local Area Unemployment Rates</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">Monthly Press Release - Statewide Jobs Data</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/pressreleases/pressreleases.shtm">Press Releases & Public Notices</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Boards and Councils</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/erb/index.shtm">Employment Relations Board</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/hab/index.htm">Hazard Abatement Board</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/iba/index.asp">Industrial Board of Appeals</a>
											</li>
											<li>
												<a href="http://www.labor.ny.gov/workforcenypartners/lwia.shtm">Local Workforce Investment Boards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workerprotection/safetyhealth/DOSH_BOARDS.shtm">Safety and Health</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforce/swib/SWIBAbout.shtm">State Workforce Investment Board</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/ui-appeal">Unemployment Insurance Appeal Board</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Forms & Publications</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/apprenticeship/apprenticeship-forms-and-publications.shtm">Apprenticeship</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/businessservices/buisness-services-forms-and-publications.shtm">Business Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/careerservices/career-services-forms-and-publications.shtm">Career Services</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/ellsformsandpublications.shtm">Employment Laws/Labor Standards</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/DEOD/deodformsandpublications.shtm">Equal Opportunity</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/immigrants/forms-and-docs.shtm">Immigrant Policies & Affairs</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/pwformsandpublications.shtm">Prevailing Wage/Public Work</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/wp/shformsandpublications.shtm">Safety and Health Documents</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/employer-forms-publications.shtm">Unemployment (Businesses)</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/formsdocs/ui/claimant-forms-and-publications.shtm">Unemployment (Claimants)</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/legal/frequently-asked-questions.shtm">Legal</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Initiatives</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://www.labor.ny.gov/apprenticeship/general/registration.shtm">Apprenticeship</a>
											</li>
											<li>
												<a href="http://www.greencareersny.com/">Green Jobs</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://careerzone.ny.gov/">CareerZone</a>
											</li>
											<li>
												<a href="http://jobzone.ny.gov/">JobZone</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://ridesafeny.com/">Ride Safe NY</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/ui/employerinfo/shared-work-program.shtm">Shared Work</a>
											</li>
										</ul>
									</div>
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/youth">Youth Portal</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
						<li>
							<a href="#">Workforce Professionals</a>
							<div class="sub-nav outer-sub-nav-2">
								<nav class="container_16 ux-content group">
									<div class="menu-column">
										<ul>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/osview.asp">New York State Career Centers</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/tools.shtm">Programs and Tools</a>
											</li>
											<li>
												<a href="http://labor.ny.gov/workforcenypartners/training-events.shtm">Training and Events</a>
											</li>
										</ul>
									</div>
								</nav>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		</li>
	</ul>
</nav>
