<!--<p class="ux-msg" data-start-date="9/8/2011" data-end-date="9/13/2011"><a href="TARGET">Example</a></p>-->




<p class="ux-msg" style="font-size:18px" data-start-date="11/02/2012" data-end-date="03/31/2013">
	<a href="/ui/2012-sandy-services.shtm">Hurricane Sandy Department Services</a>
</p>


<p class="ux-msg" data-start-date="11/08/2012" data-end-date="11/30/2012">
	<a href="http://www.labor.ny.gov/announce/email-scam.shtm"><strong>E-mail Scam Alert!</strong></a>
</p>

<p class="ux-msg" data-start-date="12/31/2012" data-end-date="2/01/2013">
	<a href="http://www.labor.ny.gov/ui/claimantinfo/ExtendedBenefits.shtm"><strong>Extended Unemployment Benefits - see the latest information</strong></a>
</p>




<p class="ux-msg" data-start-date="1/23/2012" data-end-date="1/01/2013">
	<a href="/careerservices/youth-tax-credit.shtm">
		Governor Cuomo's <strong>NY Youth Works program</strong>.
	</a>
</p>

<p class="ux-msg" data-start-date="11/1/2011" data-end-date="12/31/2013">
	<a href="/jobs/regional.shtm">
		<strong>Jobs Express</strong> - Find Job Openings In Your Area
	</a>
</p>

<!--<p class="ux-msg" data-start-date="1/11/2011" data-end-date="3/31/2012"><a href="/formsdocs/factsheets/pdfs/P427.pdf" target="_blank">Assistance Available for Localities to Help with Storm Cleanup</a></p>-->