<h2>Area Unemployment Rates</h2>
<p>
	The State Labor Department is your source for employment data in every region of the state. You'll find information broken down by major metropolitan areas as well as by county. Read the <a href="http://labor.ny.gov/stats/pressreleases/prlaus.shtm">latest report on area unemployment rates</a>.
</p>

<h2>Statewide Jobs Data</h2>
<p>
	What is the current unemployment rate in New York State? What industries gained the most jobs in the past month? You will find that information and more in our <a href="http://labor.ny.gov/stats/pressreleases/pruistat.shtm">latest job numbers report</a>. 
</p>